# ----------------------------
# App (Node.js Backend)
# ----------------------------
image:
  repository: 676206914267.dkr.ecr.us-east-1.amazonaws.com/app
  tag: nodejs-stateful-apps
  port: 3000

# ----------------------------
# PostgreSQL Configuration
# ----------------------------
postgres:
  user: postgres
  password: postgres
  db: carbooking
  port: 5432
  storage: 8Gi

# ----------------------------
# Service Configuration
# ----------------------------
service:
  name: car-booking-service
  type: ClusterIP   # Change to NodePort if needed
  port: 80

# ----------------------------
# StorageClass for EBS
# ----------------------------
storageClass:
  name: ebs-sc
  provisioner: ebs.csi.aws.com
  parameters:
    type: gp3
    fsType: ext4
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

# ----------------------------
# IngressClass (ALB)
# ----------------------------
ingressClass:
  enabled: true
  name: my-aws-ingress-class
  isDefault: "true"
  controller: ingress.k8s.aws/alb

# ----------------------------
# Ingress (ALB)
# ----------------------------
ingress:
  enabled: true
  name: ingress-nginxapp1
  appLabel: app1-nginx
  ingressClassName: my-aws-ingress-class
  lbName: app1ingressrules
  scheme: internet-facing
  path: /
  health:
    protocol: HTTP
    port: traffic-port
    path: /
    intervalSeconds: 15
    timeoutSeconds: 5
    successCodes: '200'
    healthyThreshold: 2
    unhealthyThreshold: 2
