apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ .Values.ingress.appLabel }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.lbName }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.ingress.health.protocol }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ .Values.ingress.health.port }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.health.path }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "{{ .Values.ingress.health.intervalSeconds }}"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "{{ .Values.ingress.health.timeoutSeconds }}"
    alb.ingress.kubernetes.io/success-codes: "{{ .Values.ingress.health.successCodes }}"
    alb.ingress.kubernetes.io/healthy-threshold-count: "{{ .Values.ingress.health.healthyThreshold }}"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "{{ .Values.ingress.health.unhealthyThreshold }}"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
