apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-booking
  template:
    metadata:
      labels:
        app: car-booking
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_HOST
              value: postgres
