apiVersion: v1
entries:
  car-booking:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T22:48:57.82373+05:30"
    description: A Helm chart for Node.js + PostgreSQL booking app
    digest: 4a52d0f78d87c8abc3b8cee05df5e333b999b847bcc347af8f76fdf3e8807be2
    name: car-booking
    urls:
    - https://github.com/rahul-awsdevops/helm-charts-nodejs.git/charts/car-booking-1.0.0.tgz
    version: 1.0.0
generated: "2025-08-05T22:48:57.823224+05:30"
